server:
  port: 8080

spring:
  profiles:
    # 디폴트 profile. jar or 로컬서버 실행할때 환경변수로 '--spring.profiles.active=xxx' 를 하면 환경변수값으로 override 됨 
    active: local
  servlet:
    # multipart 설정
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# custom application properties
application:
  # jwt secret key
  jwt-base64-secret: MGQzNTczY2FhMTgzNDMwZTc0MWJlYzdjYmY1NzM1YWI1YTUzNGQwOWQ2ODAwZDQwZjE5OGNiMTUwNTQwZTg4M2Y3ZGFhZDk2MGVhMzg1YzA0MmRlYTk0N2I4N2I0Yjg1YWRjYmNkYzRjZjRjNTNhOTMyNjlkMTkzZmRhZTBlNWQ=
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 2592000
  content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src 'self' * 'unsafe-inline'; img-src 'self' data:; font-src 'self' * data:"
  cors: 
    allowed-origins: 'http://localhost:4260,http://dpms.openobject.net:4260'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800